GET http://localhost:5088

// todolists

###
GET http://localhost:5088/todolists

###
GET http://localhost:5088/todolists/1

###
POST http://localhost:5088/todolists
Content-Type: application/json

{
    "Name": "testList"
}

###
PUT http://localhost:5088/todolists/1
Content-Type: application/json

{
    "Name": "updatedList"
}

###
DELETE http://localhost:5088/todolists/1

// items

###
GET http://localhost:5088/todolists/1/items

###
GET http://localhost:5088/todolists/1/items/1

###
POST http://localhost:5088/todolists/1/items
Content-Type: application/json

{
    "Description": "test item",
    "Completed": false
}

###
PUT http://localhost:5088/todolists/1/items/1
Content-Type: application/json

{
    "Description": "updated item",
    "Completed": true
}

###
DELETE http://localhost:5088/todolists/1/items/1
